language: node_js
node_js: '12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
git:
  depth: 100
deploy:
  provider: heroku
  api_key:
    secure: R/w9oQHjaGkqCrA8EJ3AUSwsmEPZmUlHcGaQfad9V7CSQ0wT9+BeB5cbE6wyVizbSXUs+qEXdgHJSVvGfAk5/84Sx51XtaMWdgw003NrkU/MdXY92yu/6O/U/pOnIS9ISGCKOXtJOeTmM8Fw9rzMbwLfqdYGvsyN9wGPrWbumLd481HDeFMFAjJvrQey0/Tpw3PJi84nneJk+zg2GH04QxVZc2ZwUNaf/7nj9pHuQgolC8+aKzTYy+ieWLfg0tsb7ObNrbTF6v5v2PM8fTrR4Lnljs70vMxo73jNuauJPW5StM3PIuono7xz4gCSBfj451ETO7ks9tUFAv9h63NpA2C9xD1f/2/xpK2EHsP/OuYxLHpYXM19azeziOXCLtRdCeKRPRgKppKaSoqUcm0hrmBgWLK7fTad6NLve34Wz7A3UwegM864mGlu8znnr/IIIPZybkQnfm0xGL7QAAtO5dWRH8KwUU4pNVIz1fawx71YM78iU3MVkKik7cEEEBk4lilrENzvjhh4RGjiQxXfRl8oHoAAzbKJR1EsNP8FyyaifstJZVXlHSCRLAYuoXAjuKONVJ7baMdzeic9bsgB+K5BTt3M+mw6U624NG4vuBBY/KDpBVe1YTCurD63AEAes+LEQKkxUoGj2sZre8WVhn5jq9u1Z/plPwbkNiqStWQ=
  app: workout-tracker-das
